name: Hello CI/CD

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Message de bienvenue
        run: echo "Bienvenue dans la CI/CD pour l'API de satisfaction !"

      - name: Date et heure du déclenchement
        run: date
